package id.web.izs.nettools.core

import android.content.res.AssetManager

/**
 * OUI vendor lookup for the WiFi Analyzer 3-row display: MAC prefix → vendor
 * name, bundled as `assets/oui.txt` (generated by `scripts/gen_oui.py` from
 * the maclookup.app JSON database, whose data derives from the IEEE public
 * registries — attribution in docs/TOOLS.md).
 *
 * One line per entry: `<prefix>\t<vendor>` where prefix is lowercase hex:
 * 6 chars = MA-L/CID (24-bit), 7 chars = MA-M/IAB (28-bit), 9 chars = MA-S
 * (36-bit). [lookup] tries the longest prefix first so 28/36-bit blocks win
 * over their parent 24-bit OUI.
 */
object OuiDb {

    @Volatile
    private var table: Map<String, String>? = null

    /** Parse [text] into a prefix → vendor map (pure, unit-tested). */
    fun parse(text: String): Map<String, String> {
        val out = HashMap<String, String>()
        for (line in text.lineSequence()) {
            val i = line.indexOf('\t')
            if (i <= 0 || i == line.lastIndex) continue
            out[line.substring(0, i)] = line.substring(i + 1)
        }
        return out
    }

    /** Load `assets/oui.txt` once; idempotent, safe from any thread. */
    fun ensureLoaded(assets: AssetManager) {
        if (table != null) return
        synchronized(this) {
            if (table != null) return
            val text = assets.open("oui.txt").use { it.readBytes().toString(Charsets.UTF_8) }
            table = parse(text)
        }
    }

    /** Longest-prefix vendor for [bssid], or "" if unknown / not loaded yet. */
    fun vendorOf(bssid: String): String {
        val t = table ?: return ""
        return lookup(t, bssid)
    }

    /**
     * Vendor for [bssid] (`aa:bb:cc:dd:ee:ff`, `aa-bb-…` or bare hex, any
     * case) inside [table]; "" when no prefix matches.
     */
    fun lookup(table: Map<String, String>, bssid: String): String {
        val hex = bssid.filter {
            it in '0'..'9' || it in 'a'..'f' || it in 'A'..'F'
        }.lowercase().take(12)
        for (len in intArrayOf(9, 7, 6)) {
            if (hex.length >= len) table[hex.substring(0, len)]?.let { return it }
        }
        return ""
    }
}
